// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkERoUvlUBUPN4QxQuQT2N13pfpJSH-Y8',
    appId: '1:126632991727:web:9de90d94bbe16715f1341a',
    messagingSenderId: '126632991727',
    projectId: 'azodha-task-12263',
    authDomain: 'azodha-task-12263.firebaseapp.com',
    storageBucket: 'azodha-task-12263.appspot.com',
    measurementId: 'G-7Q477MWS5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGCU4UvSK3Z95IR7juN8AzA7AuyRKG1t0',
    appId: '1:126632991727:android:34b8e75d1b1530d4f1341a',
    messagingSenderId: '126632991727',
    projectId: 'azodha-task-12263',
    storageBucket: 'azodha-task-12263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCj449AaU6TcZZO8sYx5w7JLAwdBxOxnc',
    appId: '1:126632991727:ios:9dd0424a45dcc8a9f1341a',
    messagingSenderId: '126632991727',
    projectId: 'azodha-task-12263',
    storageBucket: 'azodha-task-12263.appspot.com',
    iosBundleId: 'com.example.azodhaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCj449AaU6TcZZO8sYx5w7JLAwdBxOxnc',
    appId: '1:126632991727:ios:9dd0424a45dcc8a9f1341a',
    messagingSenderId: '126632991727',
    projectId: 'azodha-task-12263',
    storageBucket: 'azodha-task-12263.appspot.com',
    iosBundleId: 'com.example.azodhaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkERoUvlUBUPN4QxQuQT2N13pfpJSH-Y8',
    appId: '1:126632991727:web:b4bd12910567ca04f1341a',
    messagingSenderId: '126632991727',
    projectId: 'azodha-task-12263',
    authDomain: 'azodha-task-12263.firebaseapp.com',
    storageBucket: 'azodha-task-12263.appspot.com',
    measurementId: 'G-N5E4J46W4J',
  );

}